spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/thelilyofthenile_db
    username: thelilyofthenile_user
    password: "thelilyofthenile123!"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080